plugins = []
headers = []
redirects = []

[build]
edge_functions = "/opt/build/repo/netlify/edge-functions"
publish = "/opt/build/repo"
publishOrigin = "default"

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]

[[edge_functions]]
path = "/"
function = "geo-detect"

[functions]

  [functions."*"]